name = "ColBERT"
uuid = "7e8ad7a6-05a9-45be-b784-576440ebc08e"
authors = ["Siddhant Chaudhary <urssidd@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
